### PR TITLE
Fix/645 update mock server and fix prod crashing

### PR DESCRIPTION
**Pull request by craigyu**
# Description
JIRA issue: [FSADT2-645](https://apps.nrs.gov.bc.ca/int/jira/browse/FSADT2-645)

### Summary of changes
- Fixed a bug where empty recent activity will crash the app, @RMCampos this should be the reason the app on prod is crashing after logging in, because mock server isn't made on Prod, so basically we were testing recent activities having empty data for the first time on prod. I couldn't test if this is exactly the reason Prod is crashing though. 
- Changed mock server's `test` environment to `jest-test` to avoid confusion with our test environment on openshift
- Added configurations to the mock server if the environment is `jest-test`
- Favourite activity test is now working, it calls the mock API 🙌

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
tested manually and locally

## Checklist

- [x] I have read the [CONTRIBUTING](CONTRIBUTING.md) doc
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have already been accepted and merged

---
Thanks for the PR!

Any successful deployments (not always required) will be available below.
[Frontend](https://nr-spar-webapp-112-frontend.apps.silver.devops.gov.bc.ca/) available

Once merged, code will be promoted and handed off to following workflow run.
[Main Merge Workflow](https://github.com/bcgov/nr-spar-webapp/actions/workflows/merge-main.yml)

### CODE REVIEW

**Review by RMCampos — APPROVED** [review]
Good job! 🥇 ⭐

**Comment by craigyu** [comment]
@mgaseta changed the ariaLabel with this [commit](https://github.com/bcgov/nr-spar-webapp/pull/112/commits/ccec027066225741f65d6830201b07a0696f14be)

**Review by RMCampos — APPROVED** [review]
Good catch! LGTM

**Review by mgaseta — APPROVED** [review]
LGTM! 🥇✔🚀

**Pull request merged**
